### ISSUE TITLE
[Bug] 1.21 modeles error

### ISSUE THREAD

**Issue by Dbbtop** [quiqueck/BetterEnd#431]
### What happened?

all modeles are flat
![image](https://github.com/user-attachments/assets/42818b63-477d-45de-a8bb-9c10a7bd02cb)
![image](https://github.com/user-attachments/assets/c70fb40c-8a4c-4312-b2e8-e5dc4af30be2)

### BetterEnd

21.0.2

### BCLib

21.0.5

### Fabric API

0.100.4

### Fabric Loader

0.15.11

### Minecraft

1.20.4

**Comment by OpenBagTwo** [comment]
@Dbbtop I believe this is resolved in 21.0.9. Can you confirm and, if so, close this issue?

**Comment by Dbbtop** [comment]
![image](https://github.com/user-attachments/assets/25798cbf-3de1-41b0-95fd-f74242f8c5b2)

**Comment by Dbbtop** [comment]
![image](https://github.com/user-attachments/assets/1a22ba7e-afad-4e27-a1b9-eca319f5a8d1)

**Comment by Dbbtop** [comment]
not fixed

**Comment by votetheremess** [comment]
Still reproduces in BetterEnd 26.101.1 on MC 26.1.2. Since this has been open a while, here is the root cause and the full list of affected files.

Every tool model in BetterEnd declares `"parent": "minecraft:item/generated"`. That parent builds a flat billboarded sprite with item-like hand transforms. Tools need `minecraft:item/handheld`, which is what applies the diagonal grip. That is exactly the appearance in the screenshots above: the item renders as its inventory icon rather than as a tool.

**22 affected models in `assets/betterend/models/item/`, all currently `minecraft:item/generated`:**

`aeternium_axe`, `aeternium_hammer`, `aeternium_hoe`, `aeternium_pickaxe`, `aeternium_shovel`, `aeternium_sword`, `diamond_hammer`, `golden_hammer`, `iron_hammer`, `netherite_hammer`, `terminite_axe`, `terminite_hammer`, `terminite_hoe`, `terminite_pickaxe`, `terminite_shovel`, `terminite_sword`, `thallasium_axe`, `thallasium_hammer`, `thallasium_hoe`, `thallasium_pickaxe`, `thallasium_shovel`, `thallasium_sword`

Zero BetterEnd tool models currently use `handheld`.

The fix is one line per file:

```json
{
  "parent": "minecraft:item/handheld",
  "textures": { "layer0": "betterend:item/aeternium_pickaxe" }
}
```

For comparison, BetterNether has the same bug but only partially: 18 of its tool models are correctly `handheld` (all cincinnasite and nether_ruby tiers) and 5 are `generated` (the flaming ruby set). That partial split suggests this crept in as newer tiers were added rather than being deliberate. Filed separately as quiqueck/BetterNether#310.

Possibly also relevant to #396, which reports missing model JSONs for swords on 1.20.1. In current versions those files do exist, they just carry the wrong parent, so that report may now be this same issue.

This is client side only. A resource pack overriding the 27 model JSONs across both mods works as an interim fix for anyone who needs one before a release.

Verified by reading the shipped 26.101.1 jar directly.
